### ISSUE TITLE
[SBU] Alternative Network name Proposal

### ISSUE THREAD

**Issue by vinomaster** [sovrin-foundation/SGF-v3#1]
## Problem/Concern

Our current proposed name for the actual DID Ledger (Network) is the  **Sovrin Business Utility (SBU**. 

Some workgroup members would like to proposal alternatives names. This issue provides a discussion space for members to bring a proposal of alternative options to the Workgroup for a vote. 

Until the Workgroup decides on an alternative name, all tasks should continue to use SBU.

## Requirements

1.  Name influence and votes are limited to those participating in the DIBE Consortium GF Workgroup.
2. While the name MAY leverage **Sovrin** it is not a requirement.
3. Any proposed name MUST NOT impact our =planned association under the Sovrin DID Root namespace.
4. Proposed names SHOULD take into consideration the fact that there will be other DID Ledgers under the Sovrin DID Root Namespace that are business oriented. 
5. Proposed names MUST recognize that our DID Ledger is but an instance of the ToIP Architecture and there will be other such instances therefore the use of **ToIP** in the name is highly discouraged. 

##  Suggestion
Participants working on this proposal should try to highlight what makes our DID ledger unique so that it can be used PR activity.

**Comment by vinomaster** [comment]
@talltree (Drummond Reed) has suggested **Beryllium Network** which pertains to a rare metal (that happens to be extremely light yet strong. The notion here is that our network approach is a lightweight yet secure safe-space for enterprises.

**Comment by bharatUSAA** [comment]
Like Drummond's suggestion. Some suggestions as well -
1. **Veritas Network** - Latin for Truth is Veritas and Trust is Fiducia. 
2. **ID4BIZ** - Identity for businesses
3. **TIBU** - Trusted Identity Business Unit
4. **DINE** - Decentralized Identity Network for Enterprise. Similar along this is TINE (trusted)

**Comment by talltree** [comment]
I like Bharat's suggestions as well. I'll note that we might get into trademark issues with "Veritas Network" because, besides Harvard ("Veritas" is their motto), there is a Veritas Radio Network. 

The reason I suggested Beryllium Network (based on an original suggestion from John Jordan of BC Gov to use the name of a rare metal) is because it's distinctive without actually being an acronym or carrying any specific meaning.

**Comment by bharatUSAA** [comment]
I agree with the trademark issues and such. I'm for Beryllium Network if others are. Need more to chime in.

**Comment by aratibaliga** [comment]
Beryllium Network has  a nice ring to it. Though it's not an acronym, it might be easy to remember because of its distinctness!

**Comment by vinomaster** [comment]
I like the idea of a rare, rich mineral -- however contrary to early suggestions/implications -- [Beryllium](https://en.wikipedia.org/wiki/Beryllium) is known to be highly toxic to humans as as such may have negative connotations. 

There are [17 rare-earth elements (REE/REM)](https://en.wikipedia.org/wiki/Rare-earth_element), we could choose from these. 

Following this pathway, I propose [Didymium](https://en.wikipedia.org/wiki/Didymium) which is a mixture of two (2) rare earth elements: neodymium and praseodymium.  

My reasoning is as follows:
1. Spelling and [pronunciation](https://www.merriam-webster.com/dictionary/didymium?pronunciation&lang=en_us&dir=d&file=didymi01) have relevance to **DID**.
2. Etymology is derived from Greek word for **twin** which pertains to the two rare elements BUT for our purposes it pertains to us being early replica (twin) of the Sovrin Ledger.
3. Our ledger is intended to be more inviting (approachable) than Sovrin for enterprises. Didymium is typically used to enhance autumn scenery pictures by making leaves appear more vibrant. It does this by removing part of the **orange region of the color spectrum** as this group of colors tends to make certain elements of a picture appear "muddy". Oddly enough, the Sovrin logo is "orange". 

My formal proposal for this Issues (#1) and Issue #2:
* Didymium Business Utility (DBU)
* Didymium Consortium

**Comment by bharatUSAA** [comment]
@vinomaster Nice find. Interestingly Latin word [dido](https://www.wordsense.eu/dido/#Latin) means to distribute or scatter which gels with decentralization and also has DID in it. Other derivatives of the word include **diditus** and **didimus** as the above link shows. I'm sure didymium has roots here as well.

**Comment by talltree** [comment]
New suggestion: **Bedrock**

- Bedrock Business Utility
- Bedrock Consortium

Bedrock is the solid rock below which there is only rock. I worked at a gold mine in Alaska for three seasons and learned a lot about bedrock. It's the place where all the gold accumulates because the water can't "wash it down" any further (not a bad analogy for business usage either).

In this case we're talking about a ledger that is the bedrock for business trust worldwide.

**Comment by vinomaster** [comment]
Bedrock is first but we will use Didymium if bedrock fails search.

Votes 5-4 with 1 no vote.

**Comment by vinomaster** [comment]
Next step is to do a preliminary trademark search.
