### ISSUE TITLE
[SBU] Member Technical and Organizational Policies

### ISSUE THREAD

**Issue by bharatUSAA** [sovrin-foundation/SGF-v3#10]
## Problem/Concern

Under controlled documents, there is a member_top.md file which corresponds to the Member Technical and Organizational Policies file. The wording seems for the most part very close to the Member Technical Policies document. Question is - do we need this file as well? 

## Proposed Solution
Group to review and decide on these policy documents to avoid duplication of material.

**Comment by vinomaster** [comment]
1. Rename Tech Policies w/Member Tops
2. Rename Subscriber TOPS to Endorser Tops
3. Revise Endorser Tops

**Comment by vinomaster** [comment]
1 and 2 above done; @bharatUSAA to handle 3.

**Comment by bharatUSAA** [comment]
Completed this and a pull request has been submitted.

**Comment by bharatUSAA** [comment]
Task completed
