### ISSUE TITLE
[SBU] DIBE document template heading section and copyright section

### ISSUE THREAD

**Issue by bharatUSAA** [sovrin-foundation/SGF-v3#11]
## Problem/Concern

Every DIBE document should have a heading section describing what the document is about and the details in a table, similar to the Sovrin Foundation documents. Also a copyright string needs to be created for DIBE documents that can be added to the very bottom of every document.

## Proposed Solution
Create the language for the heading section and the copyright sections and put it in a template file on github so that authors can drag and drop and edit them into each document.

**Comment by vinomaster** [comment]
Add a template to ```/_process``` folder.
Resolved in commit 95b24a2
