### ISSUE TITLE
[SBU] Public write and read

### ISSUE THREAD

**Issue by bharatUSAA** [sovrin-foundation/SGF-v3#12]
## Problem/Concern
In the SBU network, as all participants are businesses and the ledger is permissioned, we need to firm up what "public" means in terms of Public Write and Public read policy.

## Proposed Solution
For DIBE SBU network, modify the glossary, ledger access policies to either remove the notion of public read/write or modify the definition of 'public' within the permissioned ledger framework.

**Comment by vinomaster** [comment]
resolved in [commit](https://github.com/sovrin-foundation/SGF-v3/commit/bc859ac39be85c8ba46c9a65ebc33883ca3c6e42)
some issues deferred to #25 and #24
