### ISSUE TITLE
[SBU] Member business policies - Transition Section

### ISSUE THREAD

**Issue by bharatUSAA** [sovrin-foundation/SGF-v3#19]
## Problem/Concern
The Transition section of the document has a date for the Founding Member Deadline which is inapplicable and needs to be changed.
* [link to problem content](http://sbu.sovrin.verify-creds.com/gf_controlled/member_business_policies/)

## Proposed Solution
Need to review as a group if the language applies to DIBE consortium and then if so, decide on a new deadline date.

**Comment by vinomaster** [comment]
Remove all data that is duplicated in termsheet

**Comment by bharatUSAA** [comment]
Set the founding member agreement signing deadline to Jan 2021 for now. Needs revision by the consortium members

**Comment by bharatUSAA** [comment]
Closing for now.
