### ISSUE TITLE
[SBU] Alternative Consortium Name Proposal

### ISSUE THREAD

**Issue by vinomaster** [sovrin-foundation/SGF-v3#2]
## Problem/Concern
Our current proposed name for the Governing Body that will operate as a non-profit to manage the Sovrin Business Utility (SBU) is the **DIBE Consortium**, where DIBE is an acronym for *Decentralized Identity Business Ecosystem*.

Some workgroup members would like to proposal alternatives names. This issue provides a discussion space for members to bring a proposal of alternative options to the Workgroup for a vote.

Until the Workgroup decides on an alternative name, all tasks should continue to use DIBE.

## Requirements
1. Name influence and votes are limited to those participating in the DIBE Consortium GF Workgroup.
2. Proposed names MUST not include references to *Sovrin* or *ToIP* 
3. Any proposed name MUST NOT impact our planned association under the Sovrin DID Root namespace.
4. Proposed names should nit be tightly coupled to the  DID Ledger name as the consortium may operate other ledgers. 

## Suggestion
Participants working on this proposal should try to highlight what makes our Consortium unique so that it can be used in PR activity when we describe the Consortium to external interested parties.

**Comment by bharatUSAA** [comment]
What is the equivalent of the reference "Sovrin Foundation" in our case? Is it "DIBE Consortium" or should we come up with something like "DI Business Foundation"? For now I will replace the Sovrin Foundation references to DIBE Consortium in the meantime. Thoughts?

**Comment by vinomaster** [comment]
@bharatUSAA  The governing body for the Sovrin Public Ledger (MainNet) is the **Sovrin Foundation**.  Until modified by resolution to this issue, the governing body for our Ledger (see #1 for proper name) is the **DIBE Consortium**. So YES, replace all occurrences of **Sovrin Foundation** with **DIBE Consortium**.

**Comment by talltree** [comment]
Interesting observation: if we include the term "Network" in the name of the network, then we wouldn't necessarily need a separate name for the consortia, except perhaps in legal docs. So, for example, if we used "Beryllium Network", it can refer to both the ledger AND the consortia, i.e., a member is just joining the Beryllium Network. 

Or, if we really need a separate name for the consortia, we could just call it the Beryllium Foundation.

**Comment by vinomaster** [comment]
@talltree I do not disagree with the premise that we can use the term "Network" in the name of the associated ledger and the governing body. However, such an approach would limit (without changing the name of the governing body) for the governing body to operate more than one  ledger (if it desired to do so). See requirement #4 above.

So At this juncture, we should recognize the proposal of:

**Beryllium Business Ledger (BBL)** which is governed by the **Beryllium Consortium**. This would allow the **Beryllium Consortium** to potential name and operate other ledgers.

**Comment by vinomaster** [comment]
As per my comment sin Issue #1,  I remain in favor of the use of "Utility" over "Ledger | Network" and "Consortium" but I disagree with the use of "Beryllium". 

My formal proposal for this Issues (#2) and Issue #1 :
* Didymium Business Utility (DBU)
* Didymium Consortium

**Comment by vinomaster** [comment]
![image](https://user-images.githubusercontent.com/505186/75100088-49838480-5597-11ea-93b8-fe8310b8c98a.png)
