### ISSUE TITLE
[SBU] Proposal to replace "metasystem" with "ecosystem"

### ISSUE THREAD

**Issue by talltree** [sovrin-foundation/SGF-v3#21]
## Problem/Concern

As the ToIP stack is now being discussed more widely, we have received feedback that the term `metasystem governance framework` is confusing, whereas the term `ecosystem governance framework` is more intuitive. This issue is to see if DIBE members agree.

* See the four layer diagram at the start of the [ToIP RFC](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0289-toip-stack/README.md).

## Proposed Solution

File a PR to replace `metasystem` with `ecosystem`.

**Comment by vinomaster** [comment]
I am open to this change but feel it is dependent on the Sovrin GF v3 framework.
The overview section is meant to derive from and build on the Sovrin GF v3:
http://sbu.sovrin.verify-creds.com/

We need this interlock topic resolved asap. IMHO is needs to be addressed in Sovrin Glossary as well.

**Comment by vinomaster** [comment]
@vinomaster will make change for Ecosystem on Overview page. All other sections mentioning metasystem should be changed.

**Comment by vinomaster** [comment]
Resolved with commit 9517b15; Once the Sovrin GF v3 updates its position around "Metasystem" we will be able to make broader changes to our Glossary and other aspects.
