### ISSUE TITLE
[BBU] Membership

### ISSUE THREAD

**Issue by aratibaliga** [sovrin-foundation/SGF-v3#30]
## Problem/Concern
1. Do we know how to handle read accesses to the ledger ? Is there a limit on reads for Non-Membership Roles ? Should this be made explicit ?
2. Link to Ledger Data Policies broken.

* [link to problem content](http://bbu.sovrin.verify-creds.com/gf_info/membership/)

## Proposed Solution
1. Needs discussion.
2. Fix broken link.

**Comment by vinomaster** [comment]
Fixed links; Ledger Access Polices Section 2.5 addresses Public Read requirements.
