### ISSUE TITLE
[SFE] Make SGF-v3 folder names meaningful

### ISSUE THREAD

**Issue by Oskar-van-Deventer** [sovrin-foundation/SGF-v3#34]
## SGF-v3 folder names are meaningless

The SGF-v3 folder names are currently bbu, helm, pdf, sbu, spu, stm and so. Even Sovrin insiders like myself have no clue what these three-letter words mean, let alone the casual visitor. We are using Github to make the work on SGF-v3 accessible to a wider group of Sovrin users and contributors. The abstract folder names work counter-productive.

* [https://github.com/sovrin-foundation/SGF-v3](https://github.com/sovrin-foundation/SGF-v3)

## Make SGF-v3 folder names meaningful

Let us make the folder names a bit more verbose and meaningful. Here are suggested folder names.

- bedrock_business_utility
- (helm = ??)
- (pdf = ??)
- sovrin_business_utility
- sovrin_public_utility
- sovrin_toip_metasystem

etcetera ...

Oskar

**Comment by vinomaster** [comment]
See [README](https://github.com/sovrin-foundation/SGF-v3#contents). More clarity will come when SF GF WG  and related Task Forces are formed. At this juncture only BBU is active here.

**Comment by Oskar-van-Deventer** [comment]
> See [README](https://github.com/sovrin-foundation/SGF-v3#contents). More clarity will come when SF GF WG and related Task Forces are formed. At this juncture only BBU is active here.

@vinomaster My point is: let us make the folder names more verbose now, such that visitors understand what they mean. I'd be happy to shoot in a PR with suggested folder-name changes, if that would help?

**Comment by vinomaster** [comment]
To what end; these folder names are used in development of content. Other than BBU which is operating perfectly fine, the other folders were created as place holders until real TF work is assigned. Visitors (who are not content developers) need not work with the repo. They should be working with the live online docs associated with each folder. The only active one at this time is BBU. This repo is not for the casual visitor., It is for TF or WG content authors.

**Comment by Oskar-van-Deventer** [comment]
@vinomaster Thanks, that answers my question and resolves my misunderstanding. Please close this issue.
