### ISSUE TITLE
[SBU] Typo in document name

### ISSUE THREAD

**Issue by bharatUSAA** [sovrin-foundation/SGF-v3#6]
## Problem/Concern
Typo in the word "technical" misspelled as "tecnhical".
* [https://github.com/bharatUSAA/SGF-v3/blob/master/sbu/docs/gf_controlled/member_tecnhical_policies.md]()

## Proposed Solution
Rename the file to member_technical_policies.md and fix all references to it so docker can build it and repos can pull it.

**Comment by bharatUSAA** [comment]
Renaming the file on local repo fixes the issue in docker build and rendering on localhost. However still can't push it to remote origin repo on github, due to issue 'everything is up-to-date'.

**Comment by vinomaster** [comment]
Resolved in commit 249a4ec8bc6d4b3bfe35ccad3341c1a6f05eb978

**Comment by vinomaster** [comment]
Fixed in PR https://github.com/sovrin-foundation/SGF-v3/commit/3ffad0123cf3280367babb10ee4f67d56b40c27d
